Corrected siren-core/pom.xml: the order of the lucene dependencies caused the following message error when running `mvn install`
> ERROR: fix your classpath to have tests-framework.jar before
lucene-core.jar! If you have already done this, then your VM's
java.util.ServiceLoader implementation is buggy and does not respect
classpath order, please report this to the vendor.

Signed-off-by: scampi <stephane.campinas@deri.org>